# Generated by Django 6.0.7 on 2026-08-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='identifiant url')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('short_description', models.TextField(blank=True, verbose_name='description courte')),
                ('price', models.PositiveIntegerField(verbose_name='Prix')),
                ('image_url', models.URLField(max_length=500, verbose_name='Adresse complète')),
                ('age', models.CharField(default='18+', verbose_name='Age conseillé')),
                ('parts_count', models.PositiveIntegerField(verbose_name='nombre de pièces')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LIMITED', 'Stock limité'), ('PREORDER', 'Précommande'), ('OUTOFSTOCK', 'Hors stock')], default='AVAILABLE', max_length=20, verbose_name='disponibilité')),
                ('rewards_points', models.PositiveIntegerField(default=0, verbose_name='points de récompense')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='identifiant url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'set LEGO',
                'verbose_name_plural': 'sets LEGO',
                'ordering': ['-created_at'],
            },
        ),
    ]
